# .readthedocs.yaml

version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
