# .readthedocs.yaml

version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Python configuration for installing dependencies
python:
  version: ">=3.8"  # Specify Python version
  #install:
  #  - requirements: requirements.txt  # Install dependencies listed in a requirements file (if applicable)